new_local_repository(
    name="opencv3",
    path="/usr/local",
    build_file="opencv3.BUILD")

new_local_repository(
    name="local",
    path="/usr/local",
    build_file="local.BUILD")

new_local_repository(
    name="cuda",
    path="/usr/local/cuda",
    build_file="cuda.BUILD")

